baseurl                 = "https://www.stackplus.co/"
title                   = "StackPlus Networks"
theme                   = "splus-theme"
# themesDir             = "../.."
languageCode            = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage  = "es"
# Enable Google Analytics by entering your tracking code
googleAnalytics         = ""

# Define the number of posts per page
paginate                = 10

[menu]

# Main menu

[[menu.main]]
    name        = "Home"
    url         = "/"
    weight      = 1

[[menu.main]]
    name        = "Services"
    url         = "/#services"
    weight      = 2

[[menu.main]]
    name        = "Partners"
    url         = "/#partners"
    weight      = 3

[[menu.main]]
    name        = "clients"
    url         = "/#clients"
    weight      = 4

[[menu.main]]
    name        = "Contact"
    url         = "/contact/"
    weight      = 5

# Top bar social links menu

[[menu.topbar]]
    weight      = 1
    name        = "GitHub"
    url         = "https://github.com/stackplus/"
    pre         = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Facebook"
    url = "http://facebook.com/stackplus"
    pre = "<i class='fab fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 3
    name = "Twitter"
    url = "http://twitter.com/stackplus_col"
    pre = "<i class='fab fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 4
    name = "Email"
    url = "mailto:info@stackplus.co"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "StackPlus"
    defaultKeywords = [
      "stackplus", "network", "sdn", "kubernetes", "cloud", "go", "python",
      "automation", "wireless", "security", "google", "gcloud", "aws", "azure",
      "ibm", "oracle", "openshift", "docker", "virtualization"
      ]
    defaultDescription = "StackPlus: Soluciones de nueva generacion"

    # Google Maps API key (if not set will default to not passing a key.)
    # googleMapsApiKey = ""

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "marsala"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "info@stackplus.co"

    about_us = "<p>StackPlus Networks.</p>"
    copyright = "Copyright (c) 2014 - 2018, StackPlus; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo.png"
    address = """<p><strong>STACKPLUS SAS</strong>
        <br>Bogota
        <br>
        <strong>Colombia</strong>
      </p>
      """
    latitude = "4.6349009"
    longitude = "-74.0710104"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

[params.maintenance]
    enable = false

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Contacto info@stackplus.co</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = false
    tags = false
    search = false

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find items
    # at 'data/carousel'.

[params.services]
    enable = true
    # All services are defined in their own files. You can find items
    # at 'data/services'.
    id = "services"
    title = "Servicios"
    subtitle = ""

[params.partners]
    enable = true
    # All clients are defined in their own files. You can find items
    # at 'data/partners'.
    id = "partners"
    title = "Nuestros Aliados"
    subtitle = ""

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find items
    # at 'data/testimonials'.
    title = "Testimonios"
    subtitle = "Hemos trabajado con muchos clientes y siempre nos gusta escuchar que son felices y satisfechos con nuestros servicios. Echa un vistazo a lo que dijeron nuestros clientes sobre nosotros."

[params.see_more]
    enable = false
    icon = "fa fa-file-code-o"
    title = "¿Quieres ver mas?"
    subtitle = ""
    link_url = "#"
    link_text = "Ver otras paginas de inicio"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find items
    # at 'data/clients'.
    id = "clients"
    title = "Nuestros Clientes"
    subtitle = ""

[params.recent_posts]
    enable = false
    title = "Entradas recientes en nuestro blog"
    subtitle = ""
